duser@8395372068e0:~$ python Conv1_08-12-18.py 
Using TensorFlow backend.
X_train shape: (11739, 227, 227, 3)
11739 train samples
2935 test samples
2018-12-08 14:24:30.389461
Train on 11739 samples, validate on 2935 samples
Epoch 1/15
2018-12-08 14:24:30.641779: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-12-08 14:24:31.030363: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties: 
name: Tesla V100-DGXS-32GB major: 7 minor: 0 memoryClockRate(GHz): 1.53
pciBusID: 0000:07:00.0
totalMemory: 31.73GiB freeMemory: 31.05GiB
2018-12-08 14:24:31.376028: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 1 with properties: 
name: Tesla V100-DGXS-32GB major: 7 minor: 0 memoryClockRate(GHz): 1.53
pciBusID: 0000:08:00.0
totalMemory: 31.74GiB freeMemory: 31.32GiB
2018-12-08 14:24:31.762898: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 2 with properties: 
name: Tesla V100-DGXS-32GB major: 7 minor: 0 memoryClockRate(GHz): 1.53
pciBusID: 0000:0e:00.0
totalMemory: 31.74GiB freeMemory: 31.32GiB
2018-12-08 14:24:32.126543: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 3 with properties: 
name: Tesla V100-DGXS-32GB major: 7 minor: 0 memoryClockRate(GHz): 1.53
pciBusID: 0000:0f:00.0
totalMemory: 31.74GiB freeMemory: 31.32GiB
2018-12-08 14:24:32.126627: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0, 1, 2, 3
2018-12-08 14:24:33.153747: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-12-08 14:24:33.153790: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 1 2 3 
2018-12-08 14:24:33.153801: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N Y Y Y 
2018-12-08 14:24:33.153809: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 1:   Y N Y Y 
2018-12-08 14:24:33.153817: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 2:   Y Y N Y 
2018-12-08 14:24:33.153825: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 3:   Y Y Y N 
2018-12-08 14:24:33.156108: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 30126 MB memory) -> physical GPU (device: 0, name: Tesla V100-DGXS-32GB, pci bus id: 0000:07:00.0, compute capability: 7.0)
2018-12-08 14:24:33.156508: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 30387 MB memory) -> physical GPU (device: 1, name: Tesla V100-DGXS-32GB, pci bus id: 0000:08:00.0, compute capability: 7.0)
2018-12-08 14:24:33.156848: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:2 with 30387 MB memory) -> physical GPU (device: 2, name: Tesla V100-DGXS-32GB, pci bus id: 0000:0e:00.0, compute capability: 7.0)
2018-12-08 14:24:33.157151: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:3 with 30387 MB memory) -> physical GPU (device: 3, name: Tesla V100-DGXS-32GB, pci bus id: 0000:0f:00.0, compute capability: 7.0)
11739/11739 [==============================] - 20s 2ms/step - loss: 2.4065 - acc: 0.1909 - val_loss: 2.1849 - val_acc: 0.2545
Epoch 2/15
11739/11739 [==============================] - 17s 1ms/step - loss: 2.1349 - acc: 0.2548 - val_loss: 2.1192 - val_acc: 0.2549
Epoch 3/15
11739/11739 [==============================] - 17s 1ms/step - loss: 2.0191 - acc: 0.2807 - val_loss: 2.0888 - val_acc: 0.2549
Epoch 4/15
11739/11739 [==============================] - 18s 2ms/step - loss: 1.9231 - acc: 0.3143 - val_loss: 2.0184 - val_acc: 0.2852
Epoch 5/15
11739/11739 [==============================] - 18s 2ms/step - loss: 1.7898 - acc: 0.3736 - val_loss: 2.0248 - val_acc: 0.2811
Epoch 6/15
11739/11739 [==============================] - 15s 1ms/step - loss: 1.6659 - acc: 0.4283 - val_loss: 1.9853 - val_acc: 0.3073
Epoch 7/15
11739/11739 [==============================] - 18s 2ms/step - loss: 1.4544 - acc: 0.5121 - val_loss: 2.0678 - val_acc: 0.3046
Epoch 8/15
11739/11739 [==============================] - 18s 2ms/step - loss: 1.2560 - acc: 0.5930 - val_loss: 2.1248 - val_acc: 0.2998
Epoch 9/15
11739/11739 [==============================] - 17s 1ms/step - loss: 1.0408 - acc: 0.6693 - val_loss: 2.2466 - val_acc: 0.3220
Epoch 10/15
11739/11739 [==============================] - 18s 2ms/step - loss: 0.8344 - acc: 0.7461 - val_loss: 2.3754 - val_acc: 0.2988
Epoch 11/15
11739/11739 [==============================] - 17s 1ms/step - loss: 0.6656 - acc: 0.8088 - val_loss: 2.5542 - val_acc: 0.2974
Epoch 12/15
11739/11739 [==============================] - 18s 2ms/step - loss: 0.5295 - acc: 0.8542 - val_loss: 2.8450 - val_acc: 0.2736
Epoch 13/15
11739/11739 [==============================] - 17s 1ms/step - loss: 0.4189 - acc: 0.8976 - val_loss: 2.9794 - val_acc: 0.3053
Epoch 14/15
11739/11739 [==============================] - 18s 2ms/step - loss: 0.3172 - acc: 0.9300 - val_loss: 3.2336 - val_acc: 0.2719
Epoch 15/15
11739/11739 [==============================] - 17s 1ms/step - loss: 0.2488 - acc: 0.9507 - val_loss: 3.4650 - val_acc: 0.2719
Traceback (most recent call last):
  File "Conv1_08-12-18.py", line 253, in <module>
    saved_model_path = tf.contrib.saved_model.save_keras_model(model, "./saved_models")
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/saved_model/python/saved_model/keras_saved_model.py", line 104, in save_keras_model
    checkpoint_path = _export_model_json_and_variables(model, temp_export_dir)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/saved_model/python/saved_model/keras_saved_model.py", line 148, in _export_model_json_and_variables
    model.save_weights(checkpoint_prefix, save_format='tf', overwrite=True)
TypeError: save_weights() got an unexpected keyword argument 'save_format'